/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenjualan;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

/**
 *
 * @author user
 */
public class FormPetugas extends javax.swing.JFrame {
    Database dbsetting;
    String driver,database,user,pass,userLogin;
    private Object tabel;

    /**
     * Creates new form FormPetugas
     */
    public FormPetugas() {
        initComponents();
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize=this.getSize();
        if(frameSize.height > screenSize.height){
            frameSize.height=screenSize.height;
        }
        if(frameSize.width > screenSize.width){
            frameSize.width=screenSize.width;
        }
        this.setLocation((screenSize.width-frameSize.width)/2,(frameSize.height=screenSize.height)/6);
        dbsetting=new Database();
        driver=dbsetting.SettingPanel("DBDriver");
        database=dbsetting.SettingPanel("DBDatabase");
        user=dbsetting.SettingPanel("DBUsername");
        pass=dbsetting.SettingPanel("DBPassword");
        Table.setModel(tableModel);
        Tabel(Table,new int[]{90,300,340,260,100});
        setDefaultTable();
        SetEditOff();
        
    }
    int row=0;
    public void Tampil(){
        row=Table.getSelectedRow();
        IDPetugas.setText(tableModel.getValueAt(row, 0).toString());
        NamaPetugas.setText(tableModel.getValueAt(row, 1).toString());
        Alamat.setText(tableModel.getValueAt(row, 2).toString());
        Email.setText(tableModel.getValueAt(row, 3).toString());
        Telpon.setText(tableModel.getValueAt(row, 4).toString());
        Save.setEnabled(false);
        Update.setEnabled(true);
        Delete.setEnabled(true);
        SetEditOn();
    }
    
    public void BersihData(){
        IDPetugas.setText("");
        NamaPetugas.setText("");
        Alamat.setText("");
        Email.setText("");
        Telpon.setText("");
    }
    
    public void SetEditOff(){
        IDPetugas.setEnabled(false);
        NamaPetugas.setEnabled(false);
        Alamat.setEnabled(false);
        Email.setEnabled(false);
        Telpon.setEnabled(false);
    }
    
    public void SetEditOn(){
        IDPetugas.setEnabled(true);
        NamaPetugas.setEnabled(true);
        Alamat.setEnabled(true);
        Email.setEnabled(true);
        Telpon.setEnabled(true);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Telpon = new javax.swing.JTextField();
        IDPetugas = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        NamaPetugas = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Petugas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 430, 130));

        Telpon.setBackground(new java.awt.Color(19, 24, 38));
        Telpon.setForeground(new java.awt.Color(255, 255, 255));
        Telpon.setBorder(null);
        Telpon.setCaretColor(new java.awt.Color(255, 255, 255));
        Telpon.setOpaque(false);
        jLayeredPane1.add(Telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 290, 20));

        IDPetugas.setBackground(new java.awt.Color(19, 24, 38));
        IDPetugas.setForeground(new java.awt.Color(255, 255, 255));
        IDPetugas.setBorder(null);
        IDPetugas.setCaretColor(new java.awt.Color(255, 255, 255));
        IDPetugas.setOpaque(false);
        jLayeredPane1.add(IDPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 290, 20));

        Email.setBackground(new java.awt.Color(19, 24, 38));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(null);
        Email.setCaretColor(new java.awt.Color(255, 255, 255));
        Email.setOpaque(false);
        jLayeredPane1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 290, 20));

        Alamat.setBackground(new java.awt.Color(19, 24, 38));
        Alamat.setForeground(new java.awt.Color(255, 255, 255));
        Alamat.setBorder(null);
        Alamat.setCaretColor(new java.awt.Color(255, 255, 255));
        Alamat.setOpaque(false);
        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 290, 20));

        NamaPetugas.setBackground(new java.awt.Color(19, 24, 38));
        NamaPetugas.setForeground(new java.awt.Color(255, 255, 255));
        NamaPetugas.setBorder(null);
        NamaPetugas.setCaretColor(new java.awt.Color(255, 255, 255));
        NamaPetugas.setOpaque(false);
        jLayeredPane1.add(NamaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 290, 20));

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/add.png"))); // NOI18N
        Add.setToolTipText("Tambah");
        Add.setBorder(null);
        Add.setBorderPainted(false);
        Add.setContentAreaFilled(false);
        Add.setFocusPainted(false);
        Add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Add2.png"))); // NOI18N
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/save.png"))); // NOI18N
        Save.setToolTipText("Tambah");
        Save.setBorder(null);
        Save.setBorderPainted(false);
        Save.setContentAreaFilled(false);
        Save.setFocusPainted(false);
        Save.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/save2.png"))); // NOI18N
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/update.png"))); // NOI18N
        Update.setToolTipText("Update");
        Update.setBorder(null);
        Update.setBorderPainted(false);
        Update.setContentAreaFilled(false);
        Update.setFocusPainted(false);
        Update.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/update2.png"))); // NOI18N
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/cancel.png"))); // NOI18N
        Cancel.setToolTipText("Batal");
        Cancel.setBorder(null);
        Cancel.setBorderPainted(false);
        Cancel.setContentAreaFilled(false);
        Cancel.setFocusPainted(false);
        Cancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/cancel2.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, -1));

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/delete.png"))); // NOI18N
        Delete.setToolTipText("Hapus");
        Delete.setBorder(null);
        Delete.setBorderPainted(false);
        Delete.setContentAreaFilled(false);
        Delete.setFocusPainted(false);
        Delete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/delete2.png"))); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 40));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ID");
        jLayeredPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 40));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama ");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 40));

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nomor Telepon");
        jLayeredPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 40));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Bgpetugas.png"))); // NOI18N
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -50, 590, 930));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==1) {
            Tampil();
        }
    }//GEN-LAST:event_TableMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        BersihData();
        IDPetugas.requestFocus();
        Save.setEnabled(true);
        Update.setEnabled(false);
        Delete.setEnabled(false);
        SetEditOn();
    }//GEN-LAST:event_AddActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String ID=IDPetugas.getText();
        String NM=NamaPetugas.getText();
        String AM=Alamat.getText();
        String EM=Email.getText();
        String TP=Telpon.getText();
        if((ID.isEmpty()) | (NM.isEmpty()) |(AM.isEmpty()) |(EM.isEmpty())|(TP.isEmpty())){
            JOptionPane.showMessageDialog(null, "data tidak boleh kosong, silahkan dilengkapi");
            IDPetugas.requestFocus();
        }else{
            try {
                Class.forName(driver);
                Connection c = DriverManager.getConnection(database, user, pass);
                Statement s = c.createStatement();
                String SQL = "insert into tblpetugas values('"+IDPetugas.getText()+"',"+
                        "'"+NamaPetugas.getText()+"',"+
                        "'"+Alamat.getText()+"',"+
                        "'"+Email.getText()+"',"+
                        "'"+Telpon.getText()+"')";
                s.executeUpdate(SQL);
                data[0] = IDPetugas.getText();
                data[1] = NamaPetugas.getText();
                data[2] = Alamat.getText();
                data[3] = Email.getText();
                data[4] = Telpon.getText();
                tableModel.insertRow(0, data);
                s.close();
                c.close();
                BersihData();
                Save.setEnabled(false);
                SetEditOff();
            } catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String ID=IDPetugas.getText();
        String NM=NamaPetugas.getText();
        String AM=Alamat.getText();
        String EM=Email.getText();
        String TP=Telpon.getText();
        if ((ID.isEmpty()) | (NM.isEmpty()) |(AM.isEmpty()) |(EM.isEmpty())|(TP.isEmpty())) {
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong, silahkan dilengkapi");
            IDPetugas.requestFocus();
        }else {
            try {
                Class.forName(driver);
                Connection c = DriverManager.getConnection(database,user,pass);
                Statement s = c.createStatement();
                String SQL = "Update tblpetugas set namapetugas='"+NamaPetugas.getText()+"',"+
                    "alamat='"+Alamat.getText()+"',"+
                    "email='"+Email.getText()+"',"+
                    "telpon='"+Telpon.getText()+"'"+
                    "Where idpetugas='"+IDPetugas.getText()+"'";
                s.executeUpdate(SQL);
                data[0] = IDPetugas.getText();
                data[1] = NamaPetugas.getText();
                data[2] = Alamat.getText();
                data[3] = Email.getText();
                data[4] = Telpon.getText();
                tableModel.removeRow(row);
                tableModel.insertRow(row,data);
                s.close();
                c.close();
                BersihData();
                Save.setEnabled(false);
                SetEditOff();
            } catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String ID=IDPetugas.getText();
        String NM=NamaPetugas.getText();
        String AM=Alamat.getText();
        String EM=Email.getText();
        String TP=Telpon.getText();
        if ((ID.isEmpty()) | (NM.isEmpty()) |(AM.isEmpty()) |(EM.isEmpty())|(TP.isEmpty())) {
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong, silahkan dilengkapi");
            IDPetugas.requestFocus();
        }else{
            try {
                Class.forName(driver);
                Connection c = DriverManager.getConnection(database, user, pass);
                Statement s = c.createStatement();
                String SQL = "Delete From tblpetugas Where idpetugas='"+IDPetugas.getText().toString()+"'";
                s.executeUpdate(SQL);
                data[0] = IDPetugas.getText();
                data[1] = NamaPetugas.getText();
                data[2] = Alamat.getText();
                data[3] = Email.getText();
                data[4] = Telpon.getText();
                tableModel.removeRow(row);
                s.close();
                c.close();
                BersihData();
                Save.setEnabled(false);
                SetEditOff();
            } catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        BersihData();
        SetEditOff();
    }//GEN-LAST:event_CancelActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPetugas().setVisible(true);
            }
        });
    }
    
    private javax.swing.table.DefaultTableModel tableModel=getDefaultTabelModel();
    private void Tabel(javax.swing.JTable tb, int lebar[]){
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for(int i=0;i<kolom;i++){
            javax.swing.table.TableColumn tbc=tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(17);
        }
    }
    private javax.swing.table.DefaultTableModel getDefaultTabelModel() {
        return new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String [] {"ID Petugas","Nama Petugas","Alamat Petugas","Alamat E-Mail","Telpon"}
        ){
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };
    public boolean isCellEditable(int rowIndex, int columnIndex){
        return canEdit[columnIndex];
    }
};
}
    String data[]=new String[5];
    private void setDefaultTable(){
        String stat="";
        try {
            Class.forName(driver);
            Connection c = DriverManager.getConnection(database, user, pass);
            Statement s = c.createStatement();
            String SQL= "SELECT * FROM tblpetugas";
            ResultSet r= s.executeQuery(SQL);
            while(r.next()){
                data[0] = r.getString(1);
                data[1] = r.getString(2);
                data[2] = r.getString(3);
                data[3] = r.getString(4);
                data[4] = r.getString(5);
                tableModel.addRow(data);
            }
            r.close();
            s.close();
            c.close();
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Alamat;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField IDPetugas;
    private javax.swing.JTextField NamaPetugas;
    private javax.swing.JButton Save;
    private javax.swing.JTable Table;
    private javax.swing.JTextField Telpon;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
