
package aplikasipenjualan;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

/**
 *
 * @author user
 */
public class FormDataBarang extends javax.swing.JFrame {
    Database dbsetting;
    String driver,database,user,pass,userLogin;
    private Object tabel;

    /**
     * Creates new form FormBarang
     */
    public FormDataBarang() {
        initComponents();
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize=this.getSize();
        if(frameSize.height > screenSize.height){
            frameSize.height=screenSize.height;
        }
        if(frameSize.width > screenSize.width){
            frameSize.width=screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height = screenSize.height) / 6);
        dbsetting = new Database();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        Table.setModel(tableModel);
        Tabel(Table, new int[]{90,300,90,90,90,70});
        setDefaultTable();
        SetEditOff();
        TampilComboJenis();
    }
    int row=0;
    public void Tampil(){
        row = Table.getSelectedRow();
        KodeBarang.setText(tableModel.getValueAt(row, 0).toString());
        NamaBarang.setText(tableModel.getValueAt(row, 1).toString());
        KodeJenis.setSelectedItem(tableModel.getValueAt(row, 2).toString());
        HargaNet.setText(tableModel.getValueAt(row, 3).toString());
        HargaJual.setText(tableModel.getValueAt(row, 4).toString());
        Stock.setText(tableModel.getValueAt(row, 5).toString());
        Save.setEnabled(false);
        Update.setEnabled(true);
        Delete.setEnabled(true);
        SetEditOn();
    }
    public void BersihData(){
        KodeBarang.setText("");
        NamaBarang.setText("");
        KodeJenis.setSelectedIndex(0);
        Jenis.setText("");
        HargaNet.setText("");
        HargaJual.setText("");
        Stock.setText("");
    }
    public void SetEditOff(){
        KodeBarang.setEnabled(false);
        NamaBarang.setEnabled(false);
        KodeJenis.setEnabled(false);
        HargaNet.setEnabled(false);
        HargaJual.setEnabled(false);
        Stock.setEnabled(false);
    }
    public void SetEditOn(){
        KodeBarang.setEnabled(true);
        NamaBarang.setEnabled(true);
        KodeJenis.setEnabled(true);
        HargaNet.setEnabled(true);
        HargaJual.setEnabled(true);
        Stock.setEnabled(true);
    }
    private void TampilComboJenis(){
        try {
            Connection c = DriverManager.getConnection(database, user, pass);
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String SQL = "SELECT * FROM tbljenis";
            ResultSet r = s.executeQuery(SQL);
            while(r.next()){
                KodeJenis.addItem(r.getString("kodejenis"));
            }
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        KodeBarang = new javax.swing.JTextField();
        NamaBarang = new javax.swing.JTextField();
        KodeJenis = new javax.swing.JComboBox();
        Jenis = new javax.swing.JTextField();
        HargaNet = new javax.swing.JTextField();
        HargaJual = new javax.swing.JTextField();
        Stock = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Barang");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 370, 360));

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/add.png"))); // NOI18N
        Add.setToolTipText("Tambah baru");
        Add.setBorder(null);
        Add.setBorderPainted(false);
        Add.setContentAreaFilled(false);
        Add.setFocusPainted(false);
        Add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Add2.png"))); // NOI18N
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/save.png"))); // NOI18N
        Save.setToolTipText("Simpan");
        Save.setBorder(null);
        Save.setBorderPainted(false);
        Save.setContentAreaFilled(false);
        Save.setFocusPainted(false);
        Save.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/save2.png"))); // NOI18N
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/update.png"))); // NOI18N
        Update.setToolTipText("Update");
        Update.setBorder(null);
        Update.setBorderPainted(false);
        Update.setContentAreaFilled(false);
        Update.setFocusPainted(false);
        Update.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/update2.png"))); // NOI18N
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, -1, -1));

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/delete.png"))); // NOI18N
        Delete.setToolTipText("Hapus");
        Delete.setBorder(null);
        Delete.setBorderPainted(false);
        Delete.setContentAreaFilled(false);
        Delete.setFocusPainted(false);
        Delete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/delete2.png"))); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, -1, -1));

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/cancel.png"))); // NOI18N
        Cancel.setToolTipText("Batal");
        Cancel.setBorder(null);
        Cancel.setBorderPainted(false);
        Cancel.setContentAreaFilled(false);
        Cancel.setFocusPainted(false);
        Cancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/cancel2.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jenis Barang");
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Stock");
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama Barang");
        jLayeredPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode Barang");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        KodeBarang.setBackground(new java.awt.Color(19, 24, 38));
        KodeBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        KodeBarang.setForeground(new java.awt.Color(255, 255, 255));
        KodeBarang.setBorder(null);
        KodeBarang.setCaretColor(new java.awt.Color(255, 255, 255));
        KodeBarang.setDisabledTextColor(new java.awt.Color(8, 10, 33));
        KodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeBarangActionPerformed(evt);
            }
        });
        jLayeredPane1.add(KodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 290, 20));

        NamaBarang.setBackground(new java.awt.Color(19, 24, 38));
        NamaBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NamaBarang.setForeground(new java.awt.Color(255, 255, 255));
        NamaBarang.setBorder(null);
        NamaBarang.setCaretColor(new java.awt.Color(255, 255, 255));
        jLayeredPane1.add(NamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 290, 20));

        KodeJenis.setBackground(new java.awt.Color(255, 153, 51));
        KodeJenis.setMaximumRowCount(10);
        KodeJenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Jenis" }));
        KodeJenis.setToolTipText("");
        KodeJenis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        KodeJenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                KodeJenisItemStateChanged(evt);
            }
        });
        KodeJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeJenisActionPerformed(evt);
            }
        });
        jLayeredPane1.add(KodeJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 110, 30));

        Jenis.setEditable(false);
        Jenis.setBackground(new java.awt.Color(19, 24, 38));
        Jenis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jenis.setForeground(new java.awt.Color(255, 255, 255));
        Jenis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        Jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 190, 30));

        HargaNet.setBackground(new java.awt.Color(19, 24, 38));
        HargaNet.setForeground(new java.awt.Color(255, 255, 255));
        HargaNet.setBorder(null);
        jLayeredPane1.add(HargaNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 120, 20));

        HargaJual.setBackground(new java.awt.Color(19, 24, 38));
        HargaJual.setForeground(new java.awt.Color(255, 255, 255));
        HargaJual.setBorder(null);
        jLayeredPane1.add(HargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 120, 20));

        Stock.setBackground(new java.awt.Color(19, 24, 38));
        Stock.setForeground(new java.awt.Color(255, 255, 255));
        Stock.setBorder(null);
        jLayeredPane1.add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 120, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 80.png"))); // NOI18N
        jLayeredPane1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 150, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 80.png"))); // NOI18N
        jLayeredPane1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 150, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 80.png"))); // NOI18N
        jLayeredPane1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 150, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 40));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kode Jenis");
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Harga Net");
        jLayeredPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Harga Jual");
        jLayeredPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 79.png"))); // NOI18N
        jLayeredPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -170, 890, 990));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==1) {
            Tampil();
        }
    }//GEN-LAST:event_TableMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        BersihData();
        KodeBarang.requestFocus();
        Save.setEnabled(true);
        Update.setEnabled(false);
        Delete.setEnabled(false);
        SetEditOn();
    }//GEN-LAST:event_AddActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String KB=KodeBarang.getText();
        String NB=NamaBarang.getText();
        String KJ=KodeJenis.getSelectedItem().toString();
        String HN=HargaNet.getText();
        String HJ=HargaJual.getText();
        String ST=Stock.getText();
        if((KB.isEmpty()) | (NB.isEmpty()) |(KJ.isEmpty()) |(HN.isEmpty())|(HJ.isEmpty())|(ST.isEmpty())){
            JOptionPane.showMessageDialog(null, "data tidak boleh kosong, silahkan dilengkapi");
            KodeBarang.requestFocus();
        }else{
            try {
                Class.forName(driver);
                Connection c = DriverManager.getConnection(database, user, pass);
                Statement s = c.createStatement();
                String SQL = "insert into tblbarang values('"+KodeBarang.getText()+"',"+
                    "'"+NamaBarang.getText()+"',"+
                    "'"+KodeJenis.getSelectedItem()+"',"+
                    "'"+HargaNet.getText()+"',"+
                    "'"+HargaJual.getText()+"',"+
                    "'"+Stock.getText()+"')";
                s.executeUpdate(SQL);
                data[0] = KodeBarang.getText();
                data[1] = NamaBarang.getText();
                data[2] = KodeJenis.getSelectedItem().toString();
                data[3] = HargaNet.getText();
                data[4] = HargaJual.getText();
                data[5] = Stock.getText();
                tableModel.insertRow(0, data);
                s.close();
                c.close();
                BersihData();
                Save.setEnabled(false);
                SetEditOff();
            } catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String KB=KodeBarang.getText();
        String NB=NamaBarang.getText();
        String KJ=KodeJenis.getSelectedItem().toString();
        String HN=HargaNet.getText();
        String HJ=HargaJual.getText();
        String ST=Stock.getText();
        if ((KB.isEmpty()) | (NB.isEmpty()) |(KJ.isEmpty()) |(HN.isEmpty())|(HJ.isEmpty())|(ST.isEmpty())){
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong, silahkan dilengkapi");
            KodeBarang.requestFocus();
        }else {
            try {
                Class.forName(driver);
                Connection c = DriverManager.getConnection(database,user,pass);
                Statement s = c.createStatement();
                String SQL = "Update tblbarang Set namabarang='"+NamaBarang.getText()+"',"+
                    "kodejenis='"+KodeJenis.getSelectedItem()+"',"+
                    "harganet='"+HargaNet.getText()+"',"+
                    "hargajual='"+HargaJual.getText()+"',"+
                    "stok='"+Stock.getText()+"'"+
                    "Where kodebarang='"+KodeBarang.getText()+"'";
                s.executeUpdate(SQL);
                data[0] = KodeBarang.getText();
                data[1] = NamaBarang.getText();
                data[2] = KodeJenis.getSelectedItem().toString();
                data[3] = HargaNet.getText();
                data[4] = HargaJual.getText();
                data[5] = Stock.getText();
                tableModel.removeRow(row);
                tableModel.insertRow(row,data);
                s.close();
                c.close();
                BersihData();
                Save.setEnabled(false);
                SetEditOff();
            } catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String KB=KodeBarang.getText();
        String NB=NamaBarang.getText();
        String KJ=KodeJenis.getSelectedItem().toString();
        String HN=HargaNet.getText();
        String HJ=HargaJual.getText();
        String ST=Stock.getText();
        if ((KB.isEmpty()) | (NB.isEmpty()) |(KJ.isEmpty()) |(HN.isEmpty())|(HJ.isEmpty())|(ST.isEmpty())){
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong, silahkan dilengkapi");
            KodeBarang.requestFocus();
        }else{
            try {
                Class.forName(driver);
                Connection c = DriverManager.getConnection(database, user, pass);
                Statement s = c.createStatement();
                String SQL = "Delete From tblbarang Where kodebarang='"+KodeBarang.getText().toString()+"'";
                s.executeUpdate(SQL);
                data[0] = KodeBarang.getText();
                data[1] = NamaBarang.getText();
                data[2] = KodeJenis.getSelectedItem().toString();
                data[3] = HargaNet.getText();
                data[4] = HargaJual.getText();
                data[5] = Stock.getText();
                tableModel.removeRow(row);
                s.close();
                c.close();
                BersihData();
                Save.setEnabled(false);
                SetEditOff();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Data Tidak Dapat Dihapus","Hapus Data",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        BersihData();
        SetEditOff();
    }//GEN-LAST:event_CancelActionPerformed

    private void KodeJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeJenisActionPerformed

    private void KodeJenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_KodeJenisItemStateChanged
        // TODO add your handling code here:
        try {
            Connection c = DriverManager.getConnection(database, user, pass);
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String SQL = "SELECT * FROM tbljenis where kodejenis='"+ KodeJenis.getSelectedItem().toString()+"'";
            ResultSet r = s.executeQuery(SQL);
            r.absolute(1);
            Jenis.setText(r.getString("jenis"));
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_KodeJenisItemStateChanged

    private void KodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeBarangActionPerformed

    private void JenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataBarang().setVisible(true);
            }
        });
    }
private javax.swing.table.DefaultTableModel tableModel=getDefaultTabelModel();
    private void Tabel(javax.swing.JTable tb, int lebar[]){
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for(int i=0;i<kolom;i++){
            javax.swing.table.TableColumn tbc=tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(17);
        }
    }
    private javax.swing.table.DefaultTableModel getDefaultTabelModel() {
        return new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String [] {"Kode Barang","Nama Barang","Kode Jenis", "Harga NET", "Harga Jual", "Stock"}
        ){
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };
    public boolean isCellEditable(int rowIndex, int columnIndex){
        return canEdit[columnIndex];
    }
};
}
    
    String data[]=new String[6];
    private void setDefaultTable(){
        String stat="";
        try {
            Class.forName(driver);
            Connection c = DriverManager.getConnection(database, user, pass);
            Statement s = c.createStatement();
            String SQL="SELECT * FROM tblbarang";
            ResultSet r=s.executeQuery(SQL);
            while(r.next()){
                data[0]=r.getString(1);
                data[1]=r.getString(2);
                data[2]=r.getString(3);
                data[3]=r.getString(4);
                data[4]=r.getString(5);
                data[5]=r.getString(6);
                tableModel.addRow(data);
            }
            r.close();
            s.close();
            c.close();
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField HargaJual;
    private javax.swing.JTextField HargaNet;
    private javax.swing.JTextField Jenis;
    private javax.swing.JTextField KodeBarang;
    private javax.swing.JComboBox KodeJenis;
    private javax.swing.JTextField NamaBarang;
    private javax.swing.JButton Save;
    private javax.swing.JTextField Stock;
    private javax.swing.JTable Table;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
