package aplikasipenjualan;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class FormDistributor extends javax.swing.JFrame {
    Database dbsetting;
    String driver,database,user,pass,userLogin;

    /**
     * Creates new form FormDistributor
     */
    public FormDistributor() {
        
        initComponents();
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize=this.getSize();
        if(frameSize.height > screenSize.height){
            frameSize.height=screenSize.height;
        }
        if(frameSize.width > screenSize.width){
            frameSize.width=screenSize.width;
        }
        this.setLocation((screenSize.width-frameSize.width)/2,(frameSize.height=screenSize.height)/6);
        dbsetting = new Database();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        Table.setModel(tableModel);
        Tabel(Table, new int[]{90,300,340,260,260,100});
        setDefaultTable();
        SetEditOff();
        
    }
    int row=0;
    public void Tampil(){
        row=Table.getSelectedRow();
        IDDistributor.setText(tableModel.getValueAt(row, 0).toString());
        NamaDistributor.setText(tableModel.getValueAt(row, 1).toString());
        Alamat.setText(tableModel.getValueAt(row, 2).toString());
        KotaAsal.setText(tableModel.getValueAt(row, 3).toString());
        Email.setText(tableModel.getValueAt(row, 4).toString());
        Telpon.setText(tableModel.getValueAt(row, 5).toString());
        Save.setEnabled(false);
        Update.setEnabled(true);
        Delete.setEnabled(true);
        SetEditOn();
    }
    public void BersihData(){
        IDDistributor.setText("");
        NamaDistributor.setText("");
        Alamat.setText("");
        KotaAsal.setText("");
        Email.setText("");
        Telpon.setText("");
    }
    public void SetEditOff(){
        IDDistributor.setEnabled(false);
        NamaDistributor.setEnabled(false);
        Alamat.setEnabled(false);
        KotaAsal.setEnabled(false);
        Email.setEnabled(false);
        Telpon.setEnabled(false);
    }
    public void SetEditOn(){
        IDDistributor.setEnabled(true);
        NamaDistributor.setEnabled(true);
        Alamat.setEnabled(true);
        KotaAsal.setEnabled(true);
        Email.setEnabled(true);
        Telpon.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel19 = new javax.swing.JLabel();
        Telpon = new javax.swing.JTextField();
        IDDistributor = new javax.swing.JTextField();
        KotaAsal = new javax.swing.JTextField();
        NamaDistributor = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Distributor");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nomor Telepon");
        jLayeredPane1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        Telpon.setBackground(new java.awt.Color(19, 24, 38));
        Telpon.setForeground(new java.awt.Color(255, 255, 255));
        Telpon.setBorder(null);
        Telpon.setOpaque(false);
        jLayeredPane1.add(Telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 290, 20));

        IDDistributor.setBackground(new java.awt.Color(19, 24, 38));
        IDDistributor.setForeground(new java.awt.Color(255, 255, 255));
        IDDistributor.setBorder(null);
        IDDistributor.setOpaque(false);
        jLayeredPane1.add(IDDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 290, 20));

        KotaAsal.setBackground(new java.awt.Color(19, 24, 38));
        KotaAsal.setForeground(new java.awt.Color(255, 255, 255));
        KotaAsal.setBorder(null);
        KotaAsal.setOpaque(false);
        jLayeredPane1.add(KotaAsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 290, 20));

        NamaDistributor.setBackground(new java.awt.Color(19, 24, 38));
        NamaDistributor.setForeground(new java.awt.Color(255, 255, 255));
        NamaDistributor.setBorder(null);
        NamaDistributor.setOpaque(false);
        jLayeredPane1.add(NamaDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 290, 20));

        Email.setBackground(new java.awt.Color(19, 24, 38));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(null);
        Email.setOpaque(false);
        jLayeredPane1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 290, 20));

        Alamat.setBackground(new java.awt.Color(19, 24, 38));
        Alamat.setForeground(new java.awt.Color(255, 255, 255));
        Alamat.setBorder(null);
        Alamat.setCaretColor(new java.awt.Color(255, 255, 255));
        Alamat.setOpaque(false);
        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 290, 20));

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/update.png"))); // NOI18N
        Update.setToolTipText("");
        Update.setBorder(null);
        Update.setBorderPainted(false);
        Update.setContentAreaFilled(false);
        Update.setFocusPainted(false);
        Update.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/update2.png"))); // NOI18N
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/add.png"))); // NOI18N
        Add.setToolTipText("");
        Add.setBorder(null);
        Add.setBorderPainted(false);
        Add.setContentAreaFilled(false);
        Add.setFocusPainted(false);
        Add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Add2.png"))); // NOI18N
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/cancel.png"))); // NOI18N
        Cancel.setToolTipText("");
        Cancel.setBorder(null);
        Cancel.setBorderPainted(false);
        Cancel.setContentAreaFilled(false);
        Cancel.setFocusPainted(false);
        Cancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/cancel2.png"))); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/save.png"))); // NOI18N
        Save.setToolTipText("");
        Save.setBorder(null);
        Save.setBorderPainted(false);
        Save.setContentAreaFilled(false);
        Save.setFocusPainted(false);
        Save.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/save2.png"))); // NOI18N
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/delete.png"))); // NOI18N
        Delete.setToolTipText("");
        Delete.setBorder(null);
        Delete.setBorderPainted(false);
        Delete.setContentAreaFilled(false);
        Delete.setFocusPainted(false);
        Delete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/delete2.png"))); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 40));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kota Asal");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email");
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 40));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 77.png"))); // NOI18N
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 40));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama ");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ID");
        jLayeredPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 546, 449, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/DISTRIBUTORbg.png"))); // NOI18N
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -30, 590, 930));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 670));

        jLabel6.setText("Kota Asal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 250, -1, -1));

        jLabel7.setText("Telpon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 330, -1, -1));

        jLabel8.setText("Nama Distributor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, -1, -1));

        jLabel5.setText("ID Distibutor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, -1, -1));

        jLabel9.setText("Alamat");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 190, -1, -1));

        jLabel10.setText("E-Mail");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 286, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        BersihData();
        SetEditOff();
    }//GEN-LAST:event_CancelActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==1) {
            Tampil();
        }
    }//GEN-LAST:event_TableMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        BersihData();
        IDDistributor.requestFocus();
        Save.setEnabled(true);
        Update.setEnabled(false);
        Delete.setEnabled(false);
        SetEditOn();
    }//GEN-LAST:event_AddActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String ID=IDDistributor.getText();
        String NM=NamaDistributor.getText();
        String AM=Alamat.getText();
        String KT=KotaAsal.getText();
        String EM=Email.getText();
        String TP=Telpon.getText();
        if((ID.isEmpty()) | (NM.isEmpty()) |(AM.isEmpty()) | (KT.isEmpty()) | (EM.isEmpty())|(TP.isEmpty())){
            JOptionPane.showMessageDialog(null, "data tidak boleh kosong, silahkan dilengkapi");
            IDDistributor.requestFocus();
        }else{
            try {
                Class.forName(driver);
                Connection c = DriverManager.getConnection(database, user, pass);
                Statement s = c.createStatement();
                String SQL = "insert into tbldistributor values('"+IDDistributor.getText()+"',"+
                "'"+NamaDistributor.getText()+"',"+
                "'"+Alamat.getText()+"',"+
                "'"+KotaAsal.getText()+"',"+
                "'"+Email.getText()+"',"+
                "'"+Telpon.getText()+"')";
                s.executeUpdate(SQL);
                data[0] = IDDistributor.getText();
                data[1] = NamaDistributor.getText();
                data[2] = Alamat.getText();
                data[3] = KotaAsal.getText();
                data[4] = Email.getText();
                data[5] = Telpon.getText();
                tableModel.insertRow(0, data);
                s.close();
                c.close();
                BersihData();
                Save.setEnabled(false);
                SetEditOff();
            } catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String ID=IDDistributor.getText();
        String NM=NamaDistributor.getText();
        String AM=Alamat.getText();
        String KT=KotaAsal.getText();
        String EM=Email.getText();
        String TP=Telpon.getText();
        if ((ID.isEmpty()) | (NM.isEmpty()) |(AM.isEmpty()) |(KT.isEmpty()) | (EM.isEmpty())|(TP.isEmpty())) {
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong, silahkan dilengkapi");
            IDDistributor.requestFocus();
        }else {
            try {
                Class.forName(driver);
                Connection c = DriverManager.getConnection(database,user,pass);
                Statement s = c.createStatement();
                String SQL = "Update tbldistributor set namadistributor='"+NamaDistributor.getText()+"',"+
                "alamat='"+Alamat.getText()+"',"+
                "kotaasal='"+KotaAsal.getText()+"',"+
                "email='"+Email.getText()+"',"+
                "telpon='"+Telpon.getText()+"'"+
                "Where iddistributor='"+IDDistributor.getText()+"'";
                s.executeUpdate(SQL);
                data[0] = IDDistributor.getText();
                data[1] = NamaDistributor.getText();
                data[2] = Alamat.getText();
                data[3] = KotaAsal.getText();
                data[4] = Email.getText();
                data[5] = Telpon.getText();
                tableModel.removeRow(row);
                tableModel.insertRow(row,data);
                s.close();
                c.close();
                BersihData();
                Save.setEnabled(false);
                SetEditOff();
            } catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String ID=IDDistributor.getText();
        String NM=NamaDistributor.getText();
        String AM=Alamat.getText();
        String KT=KotaAsal.getText();
        String EM=Email.getText();
        String TP=Telpon.getText();
        if ((ID.isEmpty()) | (NM.isEmpty()) |(AM.isEmpty())|(KT.isEmpty()) |(EM.isEmpty())|(TP.isEmpty())) {
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong, silahkan dilengkapi");
            IDDistributor.requestFocus();
        }else{
            try {
                Class.forName(driver);
                Connection c = DriverManager.getConnection(database, user, pass);
                Statement s = c.createStatement();
                String SQL = "Delete From tbldistributor Where iddistributor='"+IDDistributor.getText().toString()+"'";
                s.executeUpdate(SQL);
                data[0] = IDDistributor.getText();
                data[1] = NamaDistributor.getText();
                data[2] = Alamat.getText();
                data[3] = KotaAsal.getText();
                data[4] = Telpon.getText();
                tableModel.removeRow(row);
                s.close();
                c.close();
                BersihData();
                Save.setEnabled(false);
                SetEditOff();
            } catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDistributor().setVisible(true);
            }
        });
    }

    private javax.swing.table.DefaultTableModel tableModel=getDefaultTabelModel();
    private void Tabel(javax.swing.JTable tb, int lebar[]){
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for(int i=0;i<kolom;i++){
            javax.swing.table.TableColumn tbc=tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(17);
        }
    }
    private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        return new javax.swing.table.DefaultTableModel(
        new Object[][]{},
                new String []{"ID Distributor","Nama Distributor","Alamat Distributor","Kota Asal","Alamat E-Mail","Telpon"}
        ){
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };
            public boolean isCellEditable(int rowIndex, int coloumnIndex){
                return canEdit[coloumnIndex];
            }
        };
    }
    String data[]=new String[6];
    private void setDefaultTable(){
        String stat="";
        try {
            Class.forName(driver);
            Connection c = DriverManager.getConnection(database,user, pass);
            Statement s = c.createStatement();
            String SQL="SELECT * FROM tbldistributor";
            ResultSet r=s.executeQuery(SQL);
            while(r.next()){
                data[0] = r.getString(1);
                data[1] = r.getString(2);
                data[2] = r.getString(3);
                data[3] = r.getString(4);
                data[4] = r.getString(5);
                data[5] = r.getString(6);
                tableModel.addRow(data);
            }
            r.close();
            s.close();
            c.close();
        } catch (Exception ex) {
                System.err.println(ex.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Alamat;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField IDDistributor;
    private javax.swing.JTextField KotaAsal;
    private javax.swing.JTextField NamaDistributor;
    private javax.swing.JButton Save;
    private javax.swing.JTable Table;
    private javax.swing.JTextField Telpon;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
