package aplikasipenjualan;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
import javax.swing.*;
import java.awt.event.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents();
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(ToggleTransaksi);
        buttonGroup.add(ToggleFile);
        PanelTransaksi.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DaftarReport = new javax.swing.JButton();
        ToggleTransaksi = new javax.swing.JToggleButton();
        ToggleFile = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        PanelFIle = new javax.swing.JLayeredPane();
        panel1 = new javax.swing.JPanel();
        Distributor = new javax.swing.JButton();
        Petugas = new javax.swing.JButton();
        JenisBarang = new javax.swing.JButton();
        DataBarang = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelTransaksi = new javax.swing.JLayeredPane();
        panel2 = new javax.swing.JPanel();
        BarangMasuk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Penjualan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        DaftarReport.setBackground(new java.awt.Color(204, 204, 204));
        DaftarReport.setFont(new java.awt.Font("Agency FB", 0, 21)); // NOI18N
        DaftarReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/report.png"))); // NOI18N
        DaftarReport.setToolTipText("Buka Form Daftar Report");
        DaftarReport.setBorder(null);
        DaftarReport.setBorderPainted(false);
        DaftarReport.setContentAreaFilled(false);
        DaftarReport.setDefaultCapable(false);
        DaftarReport.setFocusPainted(false);
        DaftarReport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/report2.png"))); // NOI18N
        DaftarReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarReportActionPerformed(evt);
            }
        });
        jPanel1.add(DaftarReport);
        DaftarReport.setBounds(-20, 520, 320, 100);

        ToggleTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Transaksi.png"))); // NOI18N
        ToggleTransaksi.setBorder(null);
        ToggleTransaksi.setContentAreaFilled(false);
        ToggleTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleTransaksi.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Transaksi2_1.png"))); // NOI18N
        ToggleTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(ToggleTransaksi);
        ToggleTransaksi.setBounds(30, 360, 220, 100);

        ToggleFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/File.png"))); // NOI18N
        ToggleFile.setSelected(true);
        ToggleFile.setBorder(null);
        ToggleFile.setContentAreaFilled(false);
        ToggleFile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleFile.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/File2_1.png"))); // NOI18N
        ToggleFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleFileActionPerformed(evt);
            }
        });
        jPanel1.add(ToggleFile);
        ToggleFile.setBounds(30, 230, 220, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Subbackground.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -70, 270, 790);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 660));

        PanelFIle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setOpaque(false);
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Distributor.setBackground(new java.awt.Color(204, 204, 204));
        Distributor.setFont(new java.awt.Font("Agency FB", 0, 21)); // NOI18N
        Distributor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Distributor.png"))); // NOI18N
        Distributor.setToolTipText("Buka Form Distributor");
        Distributor.setBorder(null);
        Distributor.setBorderPainted(false);
        Distributor.setContentAreaFilled(false);
        Distributor.setDefaultCapable(false);
        Distributor.setFocusPainted(false);
        Distributor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Distributor2.png"))); // NOI18N
        Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistributorActionPerformed(evt);
            }
        });
        panel1.add(Distributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 320, 100));

        Petugas.setBackground(new java.awt.Color(204, 204, 204));
        Petugas.setFont(new java.awt.Font("Agency FB", 0, 21)); // NOI18N
        Petugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Petugas.png"))); // NOI18N
        Petugas.setToolTipText("Buka Form Jenis Petugas");
        Petugas.setBorder(null);
        Petugas.setBorderPainted(false);
        Petugas.setContentAreaFilled(false);
        Petugas.setDefaultCapable(false);
        Petugas.setFocusPainted(false);
        Petugas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Petugas2.png"))); // NOI18N
        Petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetugasActionPerformed(evt);
            }
        });
        panel1.add(Petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 320, 100));

        JenisBarang.setBackground(new java.awt.Color(204, 204, 204));
        JenisBarang.setFont(new java.awt.Font("Agency FB", 0, 21)); // NOI18N
        JenisBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/JenisBarang.png"))); // NOI18N
        JenisBarang.setToolTipText("Buka Form Jenis Barang");
        JenisBarang.setBorder(null);
        JenisBarang.setBorderPainted(false);
        JenisBarang.setContentAreaFilled(false);
        JenisBarang.setDefaultCapable(false);
        JenisBarang.setFocusPainted(false);
        JenisBarang.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/JenisBarang2.png"))); // NOI18N
        JenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisBarangActionPerformed(evt);
            }
        });
        panel1.add(JenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 320, 100));

        DataBarang.setBackground(new java.awt.Color(204, 204, 204));
        DataBarang.setFont(new java.awt.Font("Agency FB", 0, 21)); // NOI18N
        DataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/DataBarang.png"))); // NOI18N
        DataBarang.setToolTipText("Buka Form Barang");
        DataBarang.setBorder(null);
        DataBarang.setBorderPainted(false);
        DataBarang.setContentAreaFilled(false);
        DataBarang.setDefaultCapable(false);
        DataBarang.setFocusPainted(false);
        DataBarang.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/DataBarang2.png"))); // NOI18N
        DataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataBarangActionPerformed(evt);
            }
        });
        panel1.add(DataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 320, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/icon4.png"))); // NOI18N
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/icon3.png"))); // NOI18N
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/icon 2.png"))); // NOI18N
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/icon1.png"))); // NOI18N
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        PanelFIle.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 830, 660));

        getContentPane().add(PanelFIle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 830, 660));

        PanelTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setOpaque(false);
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarangMasuk.setBackground(new java.awt.Color(204, 204, 204));
        BarangMasuk.setFont(new java.awt.Font("Agency FB", 0, 21)); // NOI18N
        BarangMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/barangmasuk.png"))); // NOI18N
        BarangMasuk.setToolTipText("Buka Form Barang Masuk");
        BarangMasuk.setBorder(null);
        BarangMasuk.setBorderPainted(false);
        BarangMasuk.setContentAreaFilled(false);
        BarangMasuk.setDefaultCapable(false);
        BarangMasuk.setFocusPainted(false);
        BarangMasuk.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/barangmasuk2_1.png"))); // NOI18N
        BarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangMasukActionPerformed(evt);
            }
        });
        panel2.add(BarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 320, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 44.png"))); // NOI18N
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        Penjualan.setBackground(new java.awt.Color(204, 204, 204));
        Penjualan.setFont(new java.awt.Font("Agency FB", 0, 21)); // NOI18N
        Penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/penjualan.png"))); // NOI18N
        Penjualan.setToolTipText("Buka Form Penjualan");
        Penjualan.setBorder(null);
        Penjualan.setBorderPainted(false);
        Penjualan.setContentAreaFilled(false);
        Penjualan.setDefaultCapable(false);
        Penjualan.setFocusPainted(false);
        Penjualan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/penjualan2.png"))); // NOI18N
        Penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanActionPerformed(evt);
            }
        });
        panel2.add(Penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 320, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Asset 45.png"))); // NOI18N
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        PanelTransaksi.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 830, 660));

        getContentPane().add(PanelTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 830, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/img/Background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataBarangActionPerformed
        new FormDataBarang().setVisible(true);
    }//GEN-LAST:event_DataBarangActionPerformed

    private void JenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisBarangActionPerformed
        new FormJenis().setVisible(true);
    }//GEN-LAST:event_JenisBarangActionPerformed

    private void PetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetugasActionPerformed
        new FormPetugas().setVisible(true);
    }//GEN-LAST:event_PetugasActionPerformed

    private void DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistributorActionPerformed
        new FormDistributor().setVisible(true);
    }//GEN-LAST:event_DistributorActionPerformed

    private void ToggleTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleTransaksiActionPerformed
        PanelTransaksi.setVisible(true);
        PanelFIle.setVisible(false);
        
    }//GEN-LAST:event_ToggleTransaksiActionPerformed

    private void ToggleFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleFileActionPerformed
        PanelTransaksi.setVisible(false);
        PanelFIle.setVisible(true);
        
    }//GEN-LAST:event_ToggleFileActionPerformed

    private void BarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangMasukActionPerformed
        new FormBarangMasuk().setVisible(true);
    }//GEN-LAST:event_BarangMasukActionPerformed

    private void PenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanActionPerformed
        new FormPenjualan().setVisible(true);
    }//GEN-LAST:event_PenjualanActionPerformed

    private void DaftarReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarReportActionPerformed
        new FormDaftarReport().setVisible(true);
    }//GEN-LAST:event_DaftarReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BarangMasuk;
    private javax.swing.JButton DaftarReport;
    private javax.swing.JButton DataBarang;
    private javax.swing.JButton Distributor;
    private javax.swing.JButton JenisBarang;
    private javax.swing.JLayeredPane PanelFIle;
    private javax.swing.JLayeredPane PanelTransaksi;
    private javax.swing.JButton Penjualan;
    private javax.swing.JButton Petugas;
    private javax.swing.JToggleButton ToggleFile;
    private javax.swing.JToggleButton ToggleTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
